// Seed texts for the playground's semantic-search demo table (Quotes).
//
// All lines are original, written for this project (no third-party quotes,
// nothing to license). 120 short one-liners across 12 topics, distinct
// enough that a sentence-embedding model ranks them sensibly.
//
// tools/embed-seed.mjs embeds these with the vendored model and writes the
// checked-in web/data/quotes-seed.json that the playground seeds from.

export const QUOTE_TEXTS = [
  // astronomy
  { pk: "astro-01", topic: "astronomy", text: "Through a telescope, a smudge of light becomes a spiral galaxy of a hundred billion stars." },
  { pk: "astro-02", topic: "astronomy", text: "The night sky is a time machine: every star you see is light from years ago." },
  { pk: "astro-03", topic: "astronomy", text: "A total solar eclipse turns day into night for a few impossible minutes." },
  { pk: "astro-04", topic: "astronomy", text: "Saturn's rings are made of ice and rock, some pieces as small as snowflakes." },
  { pk: "astro-05", topic: "astronomy", text: "A comet's tail always points away from the sun, pushed by the solar wind." },
  { pk: "astro-06", topic: "astronomy", text: "Black holes bend light itself, hiding everything behind the event horizon." },
  { pk: "astro-07", topic: "astronomy", text: "The Milky Way and Andromeda are drifting toward a slow collision billions of years away." },
  { pk: "astro-08", topic: "astronomy", text: "On a moonless night far from city lights, thousands of stars crowd the sky." },
  { pk: "astro-09", topic: "astronomy", text: "Meteor showers are dust from old comets burning up in our atmosphere." },
  { pk: "astro-10", topic: "astronomy", text: "The first photograph of a black hole took a telescope the size of the Earth." },
  // cooking
  { pk: "cook-01", topic: "cooking", text: "Caramelized onions take forty minutes; there is no honest shortcut." },
  { pk: "cook-02", topic: "cooking", text: "A sharp knife is safer than a dull one and makes cleaner cuts." },
  { pk: "cook-03", topic: "cooking", text: "Salt the pasta water until it tastes like the sea." },
  { pk: "cook-04", topic: "cooking", text: "Rest a roast before carving so the juices settle back into the meat." },
  { pk: "cook-05", topic: "cooking", text: "Fresh basil goes in at the end; dried oregano goes in at the start." },
  { pk: "cook-06", topic: "cooking", text: "Deglaze the pan with wine and scrape up the browned bits for the sauce." },
  { pk: "cook-07", topic: "cooking", text: "Sourdough bread rises on wild yeast, patience, and a well-fed starter." },
  { pk: "cook-08", topic: "cooking", text: "Taste as you go; the recipe is a map, not the territory." },
  { pk: "cook-09", topic: "cooking", text: "A cast-iron skillet improves with every meal you cook in it." },
  { pk: "cook-10", topic: "cooking", text: "Whisk the eggs off the heat for custard that never scrambles." },
  // gardening
  { pk: "garden-01", topic: "gardening", text: "Tomatoes want deep watering, full sun, and something to climb." },
  { pk: "garden-02", topic: "gardening", text: "Compost turns kitchen scraps into next spring's soil." },
  { pk: "garden-03", topic: "gardening", text: "Prune roses in late winter, just before the new growth wakes." },
  { pk: "garden-04", topic: "gardening", text: "Mulch keeps the roots cool, the weeds down, and the water in." },
  { pk: "garden-05", topic: "gardening", text: "Bees will find your garden if you plant lavender near the fence." },
  { pk: "garden-06", topic: "gardening", text: "Seedlings started on a windowsill still need hardening off outside." },
  { pk: "garden-07", topic: "gardening", text: "A garden is never finished; it is only ever between seasons." },
  { pk: "garden-08", topic: "gardening", text: "Rotate the vegetable beds each year so the soil can recover." },
  { pk: "garden-09", topic: "gardening", text: "Deadhead the flowers and they will bloom again out of spite." },
  { pk: "garden-10", topic: "gardening", text: "The best fertilizer is the gardener's shadow." },
  // programming
  { pk: "code-01", topic: "programming", text: "Code is read far more often than it is written; optimize for the reader." },
  { pk: "code-02", topic: "programming", text: "A failing test that reproduces the bug is half the fix." },
  { pk: "code-03", topic: "programming", text: "Name things for what they mean, not for what they are made of." },
  { pk: "code-04", topic: "programming", text: "Delete dead code; version control remembers it so you don't have to." },
  { pk: "code-05", topic: "programming", text: "The database is the part of your program that outlives your program." },
  { pk: "code-06", topic: "programming", text: "Premature optimization hides bugs behind speed nobody asked for." },
  { pk: "code-07", topic: "programming", text: "Logs are the letters your past self wrote to your future debugging session." },
  { pk: "code-08", topic: "programming", text: "An index makes one query fast and every write a little slower." },
  { pk: "code-09", topic: "programming", text: "Small pull requests get reviewed; big ones get approved unread." },
  { pk: "code-10", topic: "programming", text: "Concurrency bugs hide until the demo, then arrive all at once." },
  // music
  { pk: "music-01", topic: "music", text: "A good bass line is felt in the chest before it is heard in the ears." },
  { pk: "music-02", topic: "music", text: "The rest between the notes is where the rhythm lives." },
  { pk: "music-03", topic: "music", text: "Vinyl crackle is the sound of the room the record was played in." },
  { pk: "music-04", topic: "music", text: "Practice scales slowly; speed is a side effect of accuracy." },
  { pk: "music-05", topic: "music", text: "A minor key can make even a birthday song sound like a farewell." },
  { pk: "music-06", topic: "music", text: "Live albums capture the one night the band and the crowd agreed." },
  { pk: "music-07", topic: "music", text: "The conductor's silence before the downbeat is part of the symphony." },
  { pk: "music-08", topic: "music", text: "Headphones turn a commute into a private concert hall." },
  { pk: "music-09", topic: "music", text: "Every guitarist owns one pedal too many, and it is never enough." },
  { pk: "music-10", topic: "music", text: "A melody you cannot forget is a bug in the brain called a song." },
  // ocean
  { pk: "ocean-01", topic: "ocean", text: "Waves are born from storms far over the horizon and die on the beach." },
  { pk: "ocean-02", topic: "ocean", text: "Coral reefs are cities built by animals smaller than a grain of rice." },
  { pk: "ocean-03", topic: "ocean", text: "The tide rearranges the shoreline twice a day without asking." },
  { pk: "ocean-04", topic: "ocean", text: "Whales sing across whole oceans on frequencies we can barely hear." },
  { pk: "ocean-05", topic: "ocean", text: "Most of the deep sea has never been seen by human eyes." },
  { pk: "ocean-06", topic: "ocean", text: "Salt spray and low sun turn every harbor photogenic." },
  { pk: "ocean-07", topic: "ocean", text: "An octopus can unscrew a jar from the inside." },
  { pk: "ocean-08", topic: "ocean", text: "Sailors trust the barometer more than the color of the sky." },
  { pk: "ocean-09", topic: "ocean", text: "Bioluminescent plankton light the wake of a night boat like stars." },
  { pk: "ocean-10", topic: "ocean", text: "A message in a bottle is mail with the patience of currents." },
  // mountains
  { pk: "mtn-01", topic: "mountains", text: "Above the tree line, the wind writes the rules and grants no appeals." },
  { pk: "mtn-02", topic: "mountains", text: "Switchbacks are the mountain's way of teaching patience." },
  { pk: "mtn-03", topic: "mountains", text: "Summit photos never show the blisters that paid for them." },
  { pk: "mtn-04", topic: "mountains", text: "Glaciers carve valleys the way rivers do, just slower and colder." },
  { pk: "mtn-05", topic: "mountains", text: "Start before dawn; afternoon thunderstorms own the high ridges." },
  { pk: "mtn-06", topic: "mountains", text: "Thin air at altitude turns every staircase into a negotiation." },
  { pk: "mtn-07", topic: "mountains", text: "A cairn is a stranger's promise that the trail continues." },
  { pk: "mtn-08", topic: "mountains", text: "Snow on the peaks in June is the reservoir for the valley in August." },
  { pk: "mtn-09", topic: "mountains", text: "The mountain does not care about your schedule, only your preparation." },
  { pk: "mtn-10", topic: "mountains", text: "Alpine lakes are cold enough to reset any bad mood." },
  // coffee
  { pk: "coffee-01", topic: "coffee", text: "Espresso is nine bars of pressure and twenty-five seconds of truth." },
  { pk: "coffee-02", topic: "coffee", text: "Grind fresh; ground coffee starts forgetting its flavor in minutes." },
  { pk: "coffee-03", topic: "coffee", text: "A pour-over rewards a slow, steady spiral and punishes impatience." },
  { pk: "coffee-04", topic: "coffee", text: "Light roasts taste of the farm; dark roasts taste of the roaster." },
  { pk: "coffee-05", topic: "coffee", text: "Cold brew trades acidity for sweetness and asks twelve hours for it." },
  { pk: "coffee-06", topic: "coffee", text: "The first sip of the morning is less a drink than a ceremony." },
  { pk: "coffee-07", topic: "coffee", text: "Latte art is fluid dynamics you are allowed to drink." },
  { pk: "coffee-08", topic: "coffee", text: "Decaf at midnight is a compromise between the heart and the head." },
  { pk: "coffee-09", topic: "coffee", text: "A café is an office where the rent is paid one cup at a time." },
  { pk: "coffee-10", topic: "coffee", text: "Water is most of the cup; bad water makes bad coffee, every time." },
  // running
  { pk: "run-01", topic: "running", text: "The first mile lies; judge the run by the third." },
  { pk: "run-02", topic: "running", text: "Marathon training is mostly learning to eat and sleep on schedule." },
  { pk: "run-03", topic: "running", text: "New shoes will not make you faster, but they will make you happier." },
  { pk: "run-04", topic: "running", text: "Rest days are training days for the parts you cannot see." },
  { pk: "run-05", topic: "running", text: "A rainy run feels heroic afterward and only afterward." },
  { pk: "run-06", topic: "running", text: "Negative splits win races; even splits finish them." },
  { pk: "run-07", topic: "running", text: "The track does not flatter you; four hundred meters is always the truth." },
  { pk: "run-08", topic: "running", text: "Run the hill you fear on Tuesday and it is just a hill by Saturday." },
  { pk: "run-09", topic: "running", text: "Racing is the art of spending a fixed budget of effort perfectly." },
  { pk: "run-10", topic: "running", text: "Every runner's log is a diary written in pace and heart rate." },
  // books
  { pk: "book-01", topic: "books", text: "A library card is the cheapest passport ever issued." },
  { pk: "book-02", topic: "books", text: "The book you reread at forty is not the book you read at twenty." },
  { pk: "book-03", topic: "books", text: "Margins exist so readers can argue with authors in pencil." },
  { pk: "book-04", topic: "books", text: "A good translation is a window; a great one is a door." },
  { pk: "book-05", topic: "books", text: "The to-be-read pile grows because hope is faster than reading." },
  { pk: "book-06", topic: "books", text: "Short stories are novels with all the waiting removed." },
  { pk: "book-07", topic: "books", text: "A well-worn paperback is a love letter the owner wrote by accident." },
  { pk: "book-08", topic: "books", text: "Footnotes are where careful writers hide their best jokes." },
  { pk: "book-09", topic: "books", text: "Bookstores organize by genre; memory organizes by who recommended it." },
  { pk: "book-10", topic: "books", text: "The last page of a great book closes like a door in an empty house." },
  // weather
  { pk: "wx-01", topic: "weather", text: "Petrichor is the smell of rain landing on dust that waited all summer." },
  { pk: "wx-02", topic: "weather", text: "Count the seconds between lightning and thunder to range the storm." },
  { pk: "wx-03", topic: "weather", text: "Fog is a cloud that lost its altitude but kept its dignity." },
  { pk: "wx-04", topic: "weather", text: "The first snow makes every familiar street briefly foreign." },
  { pk: "wx-05", topic: "weather", text: "A red sky at dusk is the atmosphere showing you tomorrow's forecast." },
  { pk: "wx-06", topic: "weather", text: "Humidity is heat with a grudge." },
  { pk: "wx-07", topic: "weather", text: "Hail is rain that took the elevator up before coming down." },
  { pk: "wx-08", topic: "weather", text: "A heat wave slows the whole city to the speed of shade." },
  { pk: "wx-09", topic: "weather", text: "Wind you cannot see, but the trees report it faithfully." },
  { pk: "wx-10", topic: "weather", text: "Forecasts are probabilities; umbrellas are commitments." },
  // travel
  { pk: "travel-01", topic: "travel", text: "The best souvenirs are recipes and phrases, not fridge magnets." },
  { pk: "travel-02", topic: "travel", text: "Jet lag is your body mailing itself to the wrong time zone." },
  { pk: "travel-03", topic: "travel", text: "Night trains turn geography into a lullaby." },
  { pk: "travel-04", topic: "travel", text: "A city reveals itself at breakfast, before it dresses up for tourists." },
  { pk: "travel-05", topic: "travel", text: "Pack half the clothes and twice the curiosity." },
  { pk: "travel-06", topic: "travel", text: "Getting lost on purpose is the cheapest guided tour." },
  { pk: "travel-07", topic: "travel", text: "Airport goodbyes and arrivals are the same hall, different tears." },
  { pk: "travel-08", topic: "travel", text: "The border between tourist and traveler is drawn at the local market." },
  { pk: "travel-09", topic: "travel", text: "Old maps are wrong in facts and right in spirit." },
  { pk: "travel-10", topic: "travel", text: "Every long trip ends with a list of reasons to go back." },
];
